config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'

  get 'signup', to: 'users#new', as: 'signup'
  get 'signin', to: 'sessions#new', as: 'signin'
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :tasks
  resources :users, only: %i[new create show]
  resources :sessions, only: %i[new create destroy]
  resources :groups, only: %i[index new create show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  mount_uploader :avatar, AvatarUploader

  belongs_to :user, foreign_key: 'user_id'

  has_many :groupings
  has_many :tasks, through: :groupings

  validates :name, presence: true, length: { maximum: 20 }

  scope :alphabetical, -> { order(name: :asc) }
end

app/models/grouping.rb
class Grouping < ApplicationRecord
  belongs_to :task
  belongs_to :group
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :groupings
  has_many :groups, through: :groupings

  validates :title, presence: true, length: { maximum: 20 }
  validates :amount, presence: true, numericality: { only_integer: true }

  default_scope -> { order(created_at: :desc) }

  def group
    groups.first
  end

  def group=(group)
    gr = Group.find_by(id: group)
    groups << gr if gr
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :tasks, foreign_key: 'creator_id', class_name: 'Task'
  has_many :groups, foreign_key: 'user_id', class_name: 'Group', dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, maximum: 10 }
  default_scope -> { order(created_at: :desc) }

  def grouped_tasks
    tasks.includes(:groups).select { |t| t.groups.any? }
  end

  def external_tasks
    tasks.includes(:groups).reject { |t| t.groups.any? }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  def require_login
    redirect_to new_session_path, notice: 'You must be logged in' unless current_user
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :require_login, only: %i[index new create]

  def index
    @groups = Group.all.alphabetical
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)

    if @group.save
      redirect_to groups_path, notice: 'Group was successfully created.'
    else
      flash.now[:alert] = "Error: #{@group.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def show
    @group = Group.includes(tasks: [:creator]).find_by(id: params[:id])
  end

  private

  def group_params
    params.require(:group).permit(:name, :avatar)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    if (userx = User.find_by(name: params[:username_in]))
      session[:current_user_id] = userx.id

      redirect_to user_path(session[:current_user_id]), notice: 'Succesfully signed in'
    else
      redirect_to root_path, alert: 'Please Sign Up before continuing'
    end
  end

  def show; end

  def destroy
    session.delete(:current_user_id)

    redirect_to root_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include TasksHelper
  before_action :require_login, only: %i[index new create]

  def index
    internal = params.dig(:task, :internal)
    task_list(internal)
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.build(task_params)
    @task.group = params[:group]

    if @task.save
      redirect_to tasks_path, notice: 'Task was successfully created.'
    else
      flash.now[:alert] = "Error: #{@task.errors.full_messages.join(', ')}"
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to tasks_path, notice: 'Task was successfully updated.'
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path, notice: 'Task was successfully deleted.'
  end

  private

  def task_params
    params.require(:task).permit(:title, :amount, :group)
  end

  def total_grouped
    @total = current_user.tasks.select('task.id, group.id')
      .joins(:groups).sum(:amount)
  end

  def total_external
    @total = current_user.tasks.left_outer_joins(:groupings)
      .where(groupings: { task_id: nil }).sum(:amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user_id] = @user.id
      redirect_to user_path(session[:current_user_id])
    else
      flash.alert = "Something's wrong here"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    current_user = User.find_by(id: session[:current_user_id])
    current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def task_list(internal)
    if internal
      if params[:task][:internal] == 'true'
        @tasks = current_user.grouped_tasks
        total_grouped
        cookies[:internal] = 'true'
      else
        @tasks = current_user.external_tasks
        total_external
        cookies[:internal] = 'false'
      end
    elsif cookies[:internal] == 'true'
      @tasks = current_user.grouped_tasks
      total_grouped
    else
      @tasks = current_user.external_tasks
      total_external
    end
    @tasks
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/groups/index.html.erb
<header>
  <div class = "burger">
    <%= link_to user_path(current_user) do%>
      <i class="fa fa-bars" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class = "title">
    <h1>Groups</h1>
  </div>
  <div class = "search">
    <i class="fa fa-search" aria-hidden="true"></i>
  </div> 
</header>

<div class = "g-container">
  <ul>
    <% @groups.each do |g| %>
      <%= link_to group_path(g) do %>
        <li>
          <div class="g-icon">
            <% if g.avatar.thumb.url %>
              <%= image_tag g.avatar.url, :class => "icon" %>
            <% end %>
          </div>
          <div>
            <h3><%= g.name %></h3>
            <small>Created: <%= g.created_at.strftime('%d %b %Y') %></small>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
</div>

<footer>
  <%= link_to new_group_path do %>
    <div class = "btn-bottom">
      <div class = "btn-inner">
        <h2> Create New </h2>
      </div>
    </div>
  <% end %>
</footer>

app/views/groups/new.html.erb
<header>
  <div class = "burger">
    <%= link_to groups_path(current_user) do%>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
  <div class = "title">
    <h1>Create A Group</h1>
  </div>
  <div class = "search">
    <i class="fas fa-ellipsis-v"></i>
  </div> 
</header>

<div class = "container f">
  <%= form_with(model: @group, local: true) do |form| %>
    <div class = "container f">
      <div class = "form-wrapper">
        <%= form.text_field :name, placeholder: "Name", :class => "field" %>
        <%= form.file_field :avatar, :class => "upload" %>
      </div>

      <%= form.submit 'Create', :class => "btn" %>
  <% end %>
</div>

app/views/groups/show.html.erb
<header>
  <div class = "burger">
    <%= link_to groups_path do %>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
  <div class = "title">
    <h1><%= @group.name %></h1>
  </div>
  <div class = "search">
    <i class="fas fa-ellipsis-v"></i>
  </div> 
</header>

<div class = "container f">
  <ul>     
    <% @group.tasks.each do |t| %>
        <li>
          <div class="g-icon">
            <%= image_tag(@group.avatar.url, :class => "icon") %>
          </div>
          <div>
            <div class = "task-info">
              <p><%= t.title %></p>
              <p>$ <%= t.amount %></p>
            </div>
            <small><%= t.created_at.strftime('%d %b %Y') %> |</small>
            <small>Creator: <%= t.creator.name %></small>
          </div>
        </li>
    <% end %>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Traxapp</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/180379972d.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Poller+One&display=swap" rel="stylesheet">
  </head>

  <body>
  <main class="main">
  <div class="flash">
    <% if notice.present? %>
      <div class="notice">
        <p> <%= notice %> </p>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert">
        <p> <%= alert %> </p>
      </div>
    <% end %>
  </div>

    
      <%= yield %>
    </main>

  </body>
</html>

app/views/pages/index.html.erb
<main class="home">
  <div class="logo"><h1>Trax</h1></div>
  <div class = "home-buttons">
    <%= link_to "LOG IN", signin_path, id: "btn-signin" %>
    <%= link_to "SIGN UP", signup_path, id: "btn-signup" %>
  </div>
</main>

app/views/tasks/edit.html.erb
<header>
  <div class = "burger">
    <%= link_to tasks_path do%>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
  <div class = "title">
    <h1>New Task</h1>
  </div>
  <div class = "search">
    <i class="fas fa-ellipsis-v"></i>
  </div> 
</header>

<div class = "container f">
  <%= form_with(model: @task) do |form| %>
    <div class = "form-wrapper">
      <%= form.text_field :title, placeholder: "Title" %>
      <%= form.text_field :amount, placeholder: "Amount" %>
      
    </div>
    <%= form.submit 'Update', :class => "btn" %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<header>
  <div class = "burger">
    <%= link_to user_path(current_user) do%>
      <i class="fa fa-bars" aria-hidden="true"></i>
    <% end %>
  </div>
  <div class = "title">
    <h1>My Tasks</h1>
  </div>
  <div class = "search">
    <i class="fa fa-search" aria-hidden="true"></i>
  </div> 
</header>

<div class = "subhead">
  <p>Total amount</p>
  <h3>$ <%= @total %></h3>
</div>

<div class = "container">
  <ul>
    <% @tasks.each do |t| %>
      <li>
        <div class="g-icon">
          <% if t.groups.first.nil?%>
            <%= image_tag('https://via.placeholder.com/150', :class => "icon") %>
          <% else %>
            <%= image_tag(t.groups.first.avatar.url, :class => "icon") %>
          <% end %>
        </div>
        <div>
            <div class = "task-info">
              <p><%= t.title %></p>
              <p>$ <%= t.amount %> </p>
            </div>
            <div class = "task-bottom">
              <div class="bottom-info">
                <small><%= t.created_at.strftime('%d %b %Y') %> |</small>
                <small><%= t.groups.first.name unless t.groups.first.nil? %></small>
              </div>
              <div class="btns">
                <div class = "edit-btn">
                  <small><%= link_to "Edit", edit_task_path(t) %></small>
                </div>
                <div class = "del-btn">
                  <small><%= link_to "Delete", task_path(t), method: :delete,
                  data: { confirm: 'Are you sure?' } %></small>
                </div>
              </div>
            </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<footer>
  <%= link_to new_task_path do %>
    <div class = "btn-bottom">
      <div class = "btn-inner">
        <h2> New Task </h2>
      </div>
    </div>
  <% end %>
</footer>

app/views/tasks/new.html.erb
<header>
  <div class = "burger">
    <%= link_to tasks_path do%>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
  <div class = "title">
    <h1>New Task</h1>
  </div>
  <div class = "search">
    <i class="fas fa-ellipsis-v"></i>
  </div> 
</header>

<div class = "container f">
  <%= form_with(model: @task, local: true) do |form| %>
    <div class = "form-wrapper">
      <%= form.text_field :title, placeholder: "Title" %>
      <%= form.text_field :amount, placeholder: "$ Amount" %>
      <%= form.select :group, Group.all.collect { |g| [ g.name, g.id ] }, {:prompt => 'Select group (optional)'} %>
    </div>
    
    <%= form.submit 'Create', :class => "btn" %>
  <% end %>
</div>

app/views/users/new.html.erb
<header>
  <div class = "burger">
    <%= link_to root_path do%>
      <i class="fas fa-chevron-left"></i>
    <% end %>
  </div>
  <div class = "title">
    <h1>Sign Up</h1>
  </div>
  <div class = "search">
    <i class="fas fa-ellipsis-v"></i>
  </div> 
</header>

<div class = "container f">
  <%= form_with(model: @user) do |form| %>
    <div class = "form-wrapper">
      <%= form.text_field :name, placeholder: "Name" %>
    </div>
    <%= form.submit 'Sign Up', :class => "btn" %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class = "wrapper">
  <div class = "profile-img">
    <%= image_tag("https://placeimg.com/100/100/tech", class: "thumbnail", alt: "Profile") %>
    <h1 class = "username"><%= current_user.name %></h1>
  </div>

  <ul>
    <%= link_to tasks_path(:task => { :internal => 'true' }) do %>
      <li>
          <i class="fas fa-tasks"></i>
          <p>My Tasks</p>
      </li>
    <% end %>

    <%= link_to tasks_path(:task => { :internal => 'false' }) do %>
      <li>
        <i class="fas fa-list-alt"></i>
        <p>Other Tasks</p>
      </li>
    <% end %>

    <%= link_to groups_path do %>
      <li>
        <i class="fas fa-object-group"></i>
        <p>Groups</p>
      </li>
    <% end %>

    <%= link_to signout_path, :class => "last" do %>
      <li>
        <i class="fas fa-sign-out-alt"></i>
        <p>Logout</p>
      </li>
    <% end %>
  </ul>
</div>